### 1. Import the NUMPY package under the name np.

In [340]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [341]:
np.version.version

'1.15.4'

In [342]:
# note that np.version returns a file path from the file version
np.version

<module 'numpy.version' from '/Users/liviaclarete/.pyenv/versions/dataAnalysis/lib/python3.6/site-packages/numpy/version.py'>

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
* Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [343]:
# note that in a DataFrame eacho column represent a dimention

### method 1: using numpy.random.randn¶
It returns a sample (or samples) from the “uniform distribution” over [0, 1]

* https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html


In [344]:
# an array with 1 element
np.random.rand(1)

array([0.53593552])

In [345]:
# an array with 2 elements 
np.random.rand(2)

array([0.14178395, 0.73400328])

In [346]:
# the following parameters represent the matrix's shape

In [347]:
# an array with 3 elements in 2 dimentions
np.random.rand(2, 1, 3)

array([[[0.34871289, 0.93278014, 0.60250223]],

       [[0.8465785 , 0.13970512, 0.31886498]]])

In [348]:
# an array with 3 dimentions with 2 elements each
np.random.rand(3, 1, 2)

array([[[0.52792478, 0.13475034]],

       [[0.63960904, 0.19247413]],

       [[0.66291732, 0.05044777]]])

In [349]:
# method 1: generante random numbers passing the number of dimentions
a = np.random.rand(2, 3, 5)

In [350]:
a

array([[[0.84780027, 0.50472386, 0.5138918 , 0.52804829, 0.09019021],
        [0.08817961, 0.32831022, 0.25001884, 0.57157569, 0.35864643],
        [0.7970256 , 0.88890664, 0.14008969, 0.9031447 , 0.42940619]],

       [[0.68044859, 0.41245632, 0.84742918, 0.53427464, 0.81294566],
        [0.55217053, 0.84654722, 0.23968259, 0.37763935, 0.52965205],
        [0.82097647, 0.7579544 , 0.58147562, 0.57978549, 0.23798227]]])

#### Method 2: we can also use the function np.random.randn
It returns a sample (or samples) from the “standard normal” distribution.


https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html

In [351]:
# an array with 4 dimentions, each dimention with  3 arrays, and each arry with 2 elements
a = np.random.randn(2, # number of elements of 'outer' elements
                    3, # number of arrys inside 'inner' elements
                    5 # number of elements inside the 'inner' elements
                   )


In [352]:
a

array([[[ 0.71926077, -1.28398505, -0.07553202,  0.85070449,
          0.40261121],
        [-1.04439377, -1.06115315,  2.17391584, -0.06563862,
          0.01848277],
        [ 2.18798191, -0.13201361, -0.86580576, -0.98346715,
          0.03399142]],

       [[-0.72759545,  0.94557011,  0.19009958, -0.26881108,
         -0.12391613],
        [ 2.07203842,  0.46028015, -0.69570429, -0.50631087,
         -1.30370837],
        [-0.05942819,  1.15262612,  0.56148796,  1.94344163,
          0.35554662]]])

### method 3
We can also create an array of integer values using np.random.randit

* check it out: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html


In [394]:
# notice that the paramaters are different from np.random.rand and np.randm.randn
a = np.random.randint(5, # longest number
                      size=[
                          # number of dimentions
                          2,
                          # number of arrays in the first array
                          3, 
                          # number of elements from the second array
                          5])

### 4. Print a.

In [355]:
print(a)

[[[3 1 4 4 2]
  [2 2 2 2 2]
  [3 2 4 3 0]]

 [[0 1 4 3 1]
  [0 0 3 2 3]
  [1 0 2 4 3]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [356]:
b = np.full(
    # matrix dimention
    (5,2,3), 
    # element to fill the matrix
    1)

### 6. Print b.

In [357]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

In [358]:
a.shape

(2, 3, 5)

In [359]:
b.shape

(5, 2, 3)

### 8. Are you able to add a and b? Why or why not?

In [361]:
# in order to perform operations using arrays, they have to present the same shape
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [417]:
# using reshape function to transform the matrix structure
c = b.reshape((2, 3, 5))

In [418]:
c.shape

(2, 3, 5)

In [419]:
a.shape

(2, 3, 5)

### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [421]:
# using + as a way to concat arrays 'a' and 'c'
d = a + c

### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [422]:
print(d)

[[[2 5 2 3 2]
  [4 2 4 1 1]
  [4 4 2 1 1]]

 [[2 2 4 5 3]
  [5 5 4 1 4]
  [4 2 2 1 1]]]


### 12. Multiply a and c. Assign the result to e.

In [424]:
# using * to multiply values
e = a * c

### 13. Does e equal to a? Why or why not?

In [434]:
# yes, array 'e' is equal to 'a' because they have equal values and shape
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [435]:
e.shape

(2, 3, 5)

In [436]:
a.shape

(2, 3, 5)

### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [447]:
d_max = d.max()

In [448]:
d_min = d.min()

In [449]:
d_mean = d.mean()

### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [461]:
f = np.empty((2,3,5))


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [333]:
# your code

### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [335]:
# your code

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


In [337]:
# your code